name: ci
on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    install-dependencies:
        runs-on: ubuntu-latest
        outputs:
            cache-hit: ${{ steps.cache.outputs.cache-hit }}
        steps:
            - uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  cache: 'npm'
            - name: install dependencies
              run: npm install
    test:
        runs-on: ubuntu-latest
        needs: install-dependencies
        steps:
            - uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v4
            - run: npm ci
            - run: npm run test:ci

    type-check:
        runs-on: ubuntu-latest
        needs: install-dependencies
        steps:
            - uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v4
            - run: npm ci
            - run: npx tsc
    lint:
        runs-on: ubuntu-latest
        needs: install-dependencies
        steps:
            - uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v4
            - run: npm ci
            - run: npm run lint
    prettier:
        runs-on: ubuntu-latest
        needs: install-dependencies
        steps:
            - uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v4
            - run: npm ci
            - run: npm run prettier
